on:
  push:
    branches: [ develop ]
    paths-ignore:
      - pyproject.toml
      - laboratory/__init__.py
      - .github/**/*
      - '!.github/workflows/bumpVersion.yml'
      - CHANGELOG.md
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Update Version
jobs:
  createPullRequestWithNewVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        run: make version_updater
      - id: version_var
        run: |
          version=`./current-version.sh`
          echo "::set-output name=version::$version"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CPR_SEC }}
          commit-message: Bump version to ${{ steps.version_var.outputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          draft: false
          title: Bump version
          delete-branch: true
          labels: |
            automated pr
          reviewers: mikhailprivalov
          base: develop
          body: |
            Bump version L2 to ${{ steps.version_var.outputs.version }}
            - ${{ steps.version_var.outputs.version }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
