on:
  push:
    branches: [ develop ]
    paths:
      - laboratory/__init__.py

name: Make new tag
jobs:
  createTag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_check.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Get actual version
        id: version_check
        run: |
          version=`./current-version.sh`
          echo "::set-output name=version::v$version"

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.version_check.outputs.version }}
          message: 'New version ${{ steps.version_check.outputs.version }}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'l2-frontend/yarn.lock'

      - name: Install Dependencies
        run: make npm_install_cached

      - name: Build for production
        run: make build_prod

      - name: Make webpack_bundles.tar.gz from assets/webpack_bundles
        run: tar -czf webpack_bundles_${{ steps.version_check.outputs.version }}.tar.gz assets/webpack_bundles

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webpack_bundles.tar.gz
          path: webpack_bundles_${{ steps.version_check.outputs.version }}.tar.gz
