name: Py Django testing

on:
  push:
    branches: [ develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
  pull_request:
    branches: [ develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  build:
    runs-on: self-hosted

    env:
      SECRET_KEY: 'COMMIT_${SHORT_SHA}'

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: l2
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 1s --health-retries 25

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install libmupdf-dev
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - run: cp -r $HOME/.poetry/lib/poetry/_vendor/py3.9 $HOME/.poetry/lib/poetry/_vendor/py3.10
    - run: poetry install
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Make migrations
      run: |
        source .venv/bin/activate
        python3 manage.py makemigrations
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py migrate
    - name: Run Tests
      run: |
        source .venv/bin/activate
        python3 manage.py test
